# 调用sklearn中的函数进行归一化

In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [4]:
scaler.mean_

array([5.83416667, 3.0825    , 3.70916667, 1.16916667])

In [5]:
scaler.scale_

array([0.81019502, 0.44076874, 1.76295187, 0.75429833])

In [6]:
X_train = scaler.transform(X_train)
np.mean(X_train)

1.4691951359206237e-15

In [7]:
np.std(X_train)

1.0

In [8]:
X_test_stand = scaler.transform(X_test)
np.mean(X_test_stand)

0.017301865911564306

In [9]:
np.std(X_test_stand)

1.0106222881514342

In [10]:
knnClf = KNeighborsClassifier(n_neighbors=3)
knnClf.fit(X_train,y_train)
knnClf.score(X_test_stand,y_test)

1.0

In [11]:
knnClf.score(X_test,y_test) # 显然，如果X_test 如果不进行归一化，则分类效果会很差

0.3333333333333333

# 引入本地文件 进行 归一化处理

In [12]:
from KNNProject.preprocessing import StandardScaler
scaler = StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)
scaler.fit(X_train)
scaler.mean_

array([5.83416667, 3.0825    , 3.70916667, 1.16916667])

In [13]:
scaler.scale_

array([0.81019502, 0.44076874, 1.76295187, 0.75429833])

In [14]:
X_train = scaler.transform(X_train)
np.mean(X_train)

5.921189464667501e-17

In [15]:
np.std(X_train)

1.0

In [16]:
X_test_stand = scaler.transform(X_test)
np.mean(X_test_stand)

0.017301865911562863

In [17]:
np.std(X_test_stand)

1.0106222881514346